#!/usr/bin/env bash

set -ex
aiko_current_dir=$(cd $(dirname ${BASH_SOURCE:-$0}) && pwd)

#sed -i -r 's/^LIVEKITNAME.*/LIVEKITNAME="slax"/' $THIS/../../config
#sed -i -r 's/^NETWORK.*/NETWORK=true/' $THIS/../../config
cd ${aiko_current_dir}

. ./copy
#. ./install
set +e
. ./cleanup
set -e
. ./copy

# now run build script
SKIPINITRFS=true
cd ../../
# save $0
. ./build

# setup initrd now, to include aufs
#apt-get update
#apt-get install aufs-dkms linux-headers-$(uname -r) --yes

cd initramfs
. ./initramfs_create

mv -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
cp -vfR ${aiko_current_dir}/bootfiles/* $LIVEKITDATA/$LIVEKITNAME/boot/
