#!/usr/bin/env bash

current_dir=$(cd $(dirname $0) && pwd)

apt update
echo "firmware-ipw2x00        firmware-ipw2x00/license/accepted       boolean true" | debconf-set-selections

apt install --yes --no-install-recommends \
   firmware-linux-free \
   firmware-atheros \
   firmware-iwlwifi \
   firmware-zd1211 \
   firmware-realtek \
   firmware-bnx2 \
   firmware-brcm80211 \
   firmware-cavium \
   firmware-ipw2x00 \
   firmware-libertas \
   firmware-ti-connectivity \
   firmware-b43-installer

. ${current_dir}/../../cleanup

savechanges /tmp/010-firmware.sb
